### ISSUE TITLE
Can not receive `interface{}` type of value in request body

### ISSUE THREAD

**Issue by gitsang** [zeromicro/go-zero#2040] opened 2022-06-22 13:08 UTC
**Describe the bug**

I wish to receive any type of request body. But go-zero seems not support `interface{}` type of value.

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   type (
           CreateDemoReq {
                   Data interface{} `json:"data"`
           }
           CreateDemoResp struct{}
   )

   service Demo {
           @handler CreateDemo
           post /api/v1/demos (CreateDemoReq) returns (CreateDemoResp)
   }
   ```

2. The error is

   ```
   # curl localhost:8888/api/v1/demos -H 'Content-Type: application/json' -d '{"data": "some"}'
   error: type mismatch for field data
   ```

**Expected behavior**

Request success

**Screenshots**

**Environments (please complete the following information):**
 - OS: centos7
 - go-zero version 1.3.4
 - goctl version 1.3.5

**More description**

**Comment by kevwan** [comment] 2022-07-11 15:50
It's by design, we prefer concrete types. Closing.

**Closed by kevwan** 2022-07-11 15:50 UTC
Labels: by design

**Comment by guquan-lengyue** [comment] 2024-01-11 11:39
it work for me!
using json Unmarshal to  read interface{} type data
```go
func SaveSaveDataHandler(svcCtx *svc.ServiceContext) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		// read bytes data from body
		bytes, err := io.ReadAll(r.Body)
		if err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
			return
		}
		//  parse bytes json data to struct
		var req types.CreateDataDto
		err = json.Unmarshal(bytes, &req)
		if err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
			return
		}
		// pass params to my save data logic
		l := productVersion.NewSaveDataLogic(r.Context(), svcCtx)
		resp, err := l.SaveData(&req)
		if err != nil {
			httpx.ErrorCtx(r.Context(), w, err)
		} else {
			httpx.OkJsonCtx(r.Context(), w, resp)
		}
	}
}
```
