### ISSUE TITLE
arm linux 上跑go_zero服务，运行时出错，在windows,linux 上跑，没有问题

### ISSUE THREAD

**Issue by zhuewizz** [zeromicro/go-zero#2575] opened 2022-11-08 07:00 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by zhuewizz** [comment] 2022-11-08 07:05
[root@CUTTERBOX home]# ./server
panic: cannot statfs cgroup root: no such file or directory

goroutine 1 [running]:
github.com/zeromicro/go-zero/core/stat/internal.isCgroup2UnifiedMode.func1()
        /usr/local/go/pkg/pkg/mod/github.com/zeromicro/go-zero@v1.4.0/core/stat/internal/cgroup_linux.go:191 +0x148
sync.(*Once).doSlow(0xce6ae0, 0x7bfcc4)
        /usr/local/go/src/sync/once.go:74 +0xb8
sync.(*Once).Do(0xce6ae0, 0x7bfcc4)
        /usr/local/go/src/sync/once.go:65 +0x40
github.com/zeromicro/go-zero/core/stat/internal.isCgroup2UnifiedMode()
        /usr/local/go/pkg/pkg/mod/github.com/zeromicro/go-zero@v1.4.0/core/stat/internal/cgroup_linux.go:182 +0x24
github.com/zeromicro/go-zero/core/stat/internal.currentCgroup()
        /usr/local/go/pkg/pkg/mod/github.com/zeromicro/go-zero@v1.4.0/core/stat/internal/cgroup_linux.go:39 +0x14
github.com/zeromicro/go-zero/core/stat/internal.cpuSets()
        /usr/local/go/pkg/pkg/mod/github.com/zeromicro/go-zero@v1.4.0/core/stat/internal/cpu_linux.go:112 +0x14
github.com/zeromicro/go-zero/core/stat/internal.init.0()
        /usr/local/go/pkg/pkg/mod/github.com/zeromicro/go-zero@v1.4.0/core/stat/internal/cpu_linux.go:27 +0x14
[root@CUTTERBOX home]# uname -a
Linux CUTTERBOX 2.6.39 #9 Mon May 25 16:42:20 CST 2015 armv5tejl GNU/Linux
[root@CUTTERBOX home]#

**Comment by zhuewizz** [comment] 2022-11-08 07:39
不好意思 问题解决了 arm板是arm5 太老了 放在arm17上 运行成功

**Comment by kevwan** [comment] 2022-11-09 15:18
Good to see that the problem is fixed. Closing.

**Closed by kevwan** 2022-11-09 15:18 UTC
