### ISSUE TITLE
go-zero@v1.3.9 The generated xxxhandler.go references httpx twice! /go-zero@v1.3.9 生成的 xxxhandler.go 引用 httpx 两次

### ISSUE THREAD

**Issue by zhaobisheng** [zeromicro/go-zero#2145] opened 2022-07-14 07:56 UTC
**When using go-zero@v1.3.9 to generate the api, it is found that all handler.go references "github.com/zeromicro/go-zero/rest/httpx" twice!**
(使用go-zero@v1.3.9 生成api时发现所有handler.go引用了两次"github.com/zeromicro/go-zero/rest/httpx")

![image](https://user-images.githubusercontent.com/15358576/178926823-ac870b96-3d3a-4c97-87a7-a7761310e1df.png)

**I found the handler.tpl line 6 default had import httpx,but the variable "{{.ImportPackages}} " also  contain a httpx!**

(我发现 [handler.tpl](https://github.com/zeromicro/go-zero/blob/master/tools/goctl/api/gogen/handler.tpl#L6) 第 6 行默认有 import httpx，但变量“{{.ImportPackages}}”也包含一个 httpx！)
![image](https://user-images.githubusercontent.com/15358576/178931427-e7f71610-bd2b-472c-8911-7da371799fee.png)

**The variable "{{.ImportPackages}} " is  source from "[genhandlers.go](https://github.com/zeromicro/go-zero/blob/d70e73ec66a37a173b7fe9a01193bf85ddb555e0/tools/goctl/api/gogen/genhandlers.go#L102)"**

("{{.ImportPackages}} "的错误值来自于 "[genhandlers.go](https://github.com/zeromicro/go-zero/blob/d70e73ec66a37a173b7fe9a01193bf85ddb555e0/tools/goctl/api/gogen/genhandlers.go#L102)")
![image](https://user-images.githubusercontent.com/15358576/178931504-4b186239-0b47-45bb-94f4-ba6aff17914e.png)

**Comment by miaogaolin** [comment] 2022-07-14 08:14
same issue #2133

**Comment by LixvYang** [comment] 2022-07-15 02:32
same issure #2141    

remove one line.

**Comment by smithyj** [comment] 2022-07-16 03:20
@zhaobisheng @miaogaolin @LixvYang @kevwan 相关PR已提交 #2152

**Comment by kevwan** [comment] 2022-07-19 15:02
Duplicate of #2133

**Closed by kevwan** 2022-07-19 15:02 UTC
