### ISSUE TITLE
Why core.stores.redis.ZaddCtx score is int64 instead of float64

### ISSUE THREAD

**Issue by icestarr** [zeromicro/go-zero#2289] opened 2022-08-23 09:21 UTC
I want save a float64 to zset,but ZaddCtx only support the type of int64,is there any other way to save it?

**Comment by kevwan** [comment] 2022-08-23 12:28
It's historical reason. I guess we might need another method.

**Comment by re-dylan** [comment] 2022-08-24 03:58
Duplicate of https://github.com/zeromicro/go-zero/issues/2289

**Closed** 2022-08-24 04:11 UTC
