### ISSUE TITLE
Gateway started fail

### ISSUE THREAD

**Issue by eyjian** [zeromicro/go-zero#3855] opened 2024-01-17 02:16 UTC
**Describe the bug**
rpc services are not started, the gateway cannot be started either.

**To Reproduce**
Do not start any instances of an rpc service.

The Must statement requires that the connection is successful when the gateway starts. For the gateway, this rule is unreasonable.

**Comment by kevwan** [comment] 2024-02-04 05:57
If not check at the start, when to check the routes? For some scenarios, we load the routes from the server directly, how to know the server is started?

We can have more discussion on this. If any better solution, we'll change the implementation. Thanks!

**Comment by kevwan** [comment] 2024-02-04 05:58
duplicate of #3891

**Closed by kevwan** 2024-02-04 05:58 UTC
Labels: kind/need-more-discussion, area/gateway
